
[[language]]
name = "typst"
language-servers = ["tinymist"]


[language-server.tinymist]
command = "tinymist"
# config = { exportPdf = "onType", outputPath = "$root/target/$dir/$name", formatterMode = "typstyle" }
config = { exportPdf = "onSave", outputPath = "$root/$dir/$name", formatterMode = "typstyle" }

