general.import = [
  "base16-gruvbox-dark-hard.toml"
]

[window.padding]
x = 10
y = 10

[font]
normal = { family = "Iosevka Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 16

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

# [shell]
# program = "zellij"
# args = ["-l", "welcome"]
