# BEGIN_KITTY_THEME
# include Modus_Vivendi.conf
include Modus_Vivendi_Tinted.conf
# END_KITTY_THEME

# Set the font family to Iosevka Nerd Font
font_family Iosevka Nerd Font

# Optionally, you can specify the font size
font_size 18.0

background_opacity 0.8
window_padding_width 10

# tabs
tab_bar_style fade
tab_fade 1
active_tab_font_style   bold
inactive_tab_font_style bold
