# position = "Bottom"

enable_esc_key = true

[modules]
left = [ ["Workspaces"] ]
# center = [ "WindowTitle" ]
# center = [ "MediaPlayer" ]
right = [ ["SystemInfo"], ["KeyboardLayout"], ["Tempo"], ["Privacy"], ["Settings" ] ]

[keyboard_layout.labels]
"English (US)" = "🇺🇸"
"Arabic" = "🇩🇿"

[tempo]
clock_format = "%A %d %B %Y | %X"
weather_location = { Coordinates = [34.4051075, 4.9982626] }  # Sidi Khaled City

[appearance]
# font_name = "Iosevka Nerd Font"
# style = "Solid"
