#!/usr/bin/env bash

## Author  : Aditya Shakya (adi1090x)
## Github  : @adi1090x
#
## Applets : Brightness

# Import Current Theme
theme="$HOME/.config/rofi/applet-config.rasi"

# Brightness Info
backlight=$(printf "%.0f\n" $(brightnessctl get))
card="default"

max_backlight=$(brightnessctl max)
# Calculate the percentage of brightness
percent=$(( 100 * backlight / max_backlight ))

# Determine the backlight level based on the percentage
if [[ $percent -ge 0 && $percent -le 29 ]]; then
    level="Low"
elif [[ $percent -ge 30 && $percent -le 49 ]]; then
    level="Optimal"
elif [[ $percent -ge 50 && $percent -le 69 ]]; then
    level="High"
elif [[ $percent -ge 70 && $percent -le 100 ]]; then
    level="Peak"
fi

# Theme Elements
prompt="${backlight}%"
mesg="Device: ${card}, Level: $level"

list_col='1'
list_row='4'
win_width='400px'

# Options
layout=`cat ${theme} | grep 'USE_ICON' | cut -d'=' -f2`
if [[ "$layout" == 'NO' ]]; then
	option_1=" Increase"
	option_2=" Optimal"
	option_3=" Decrease"
	option_4=" Settings"
else
	option_1=""
	option_2=""
	option_3=""
	option_4=""
fi

# Rofi CMD
rofi_cmd() {
	rofi -theme-str "window {width: $win_width;}" \
		-theme-str "listview {columns: $list_col; lines: $list_row;}" \
		-theme-str 'textbox-prompt-colon {str: "";}' \
		-dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		-markup-rows \
		-theme ${theme}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4" | rofi_cmd
}

# Execute Command
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		brightnessctl set +5%
	elif [[ "$1" == '--opt2' ]]; then
		brightnessctl set 10
	elif [[ "$1" == '--opt3' ]]; then
		brightnessctl set 5%-
	elif [[ "$1" == '--opt4' ]]; then
		xfce4-power-manager-settings
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		run_cmd --opt1
        ;;
    $option_2)
		run_cmd --opt2
        ;;
    $option_3)
		run_cmd --opt3
        ;;
    $option_4)
		run_cmd --opt4
        ;;
esac
