;;   -*- lexical-binding: t; -*-
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-visual-line
	end-of-visual-line
	helix-go-end-line
	helix-insert
	helix-insert-exit
	kill-region
	undefined
	))

(setq mc/cmds-to-run-once
      '(
	))
