[colors.primary]
background = '#1e1e1e'
foreground = '#ffffff'

[colors.selection]
text = '#ffffff'
background = '#4a4200'

[colors.cursor]
text = '#1e1e1e'
cursor = '#d0bc00'

[colors.normal]
black   = '#000000'
red     = '#ef1900'
green   = '#1ad000'
yellow  = '#ffd600'
blue    = '#c5b200'
magenta = '#605700'
cyan    = '#d0bc00'
white   = '#dad7c0'

[colors.bright]
black   = '#878572'
red     = '#ff543f'
green   = '#61f94a'
yellow  = '#ffe24c'
blue    = '#e4d222'
magenta = '#ffed4c'
cyan    = '#fff38c'
white   = '#fffdf2'
