;;; helix-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helix-avy.el

(autoload 'helix-avy-setup "helix-avy"
"Set up Helix Mode keybindings for avy.")
(register-definition-prefixes "helix-avy" '("helix-avy-goto-word"))


;;; Generated autoloads from helix-core.el

(autoload 'helix-normal-mode "helix-core"
"Helix NORMAL state minor mode.

This is a minor mode.  If called interactively, toggle the `Helix-Normal
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `helix-normal-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'helix-mode-all "helix-core"
"Activate `helix-normal-mode' in all buffers.

Argument STATUS is passed through to `helix-mode-maybe-activate'.

(fn &optional STATUS)" t)
(autoload 'helix-mode "helix-core"
"Toggle global Helix mode." t)
(register-definition-prefixes "helix-core" '("helix-"))


;;; Generated autoloads from helix-jj.el

(autoload 'helix-jj-setup "helix-jj"
"Set up `j j' as an alternative way to exit `helix-insert-mode'.

TIMEOUT is passed `helix-jj-timeout', defaulting to 0.2.  The timeout
controls how many seconds `helix-insert-mode' waits for a second j
keypress to escape to normal mode.

(fn &optional TIMEOUT)")
(register-definition-prefixes "helix-jj" '("helix-jj-"))


;;; Generated autoloads from helix-multiple-cursors.el

(autoload 'helix-multiple-cursors-setup "helix-multiple-cursors"
"Set up Helix Mode keybindings for multiple-cursors.")
(register-definition-prefixes "helix-multiple-cursors" '("helix-multiple-cursors-"))


;;; Generated autoloads from helix-treesit.el

(autoload 'helix-expand-selection "helix-treesit"
"Expand selection to the next enclosing named tree-sitter node.

If no region is active, select the smallest named node containing
point.  Repeated invocations select increasingly larger ancestor
nodes." t)
(autoload 'helix-shrink-selection "helix-treesit"
"Shrink selection to the previous tree-sitter selection.

This reverses prior `helix-expand-selection' invocations in the
current buffer.  If no tree-sitter selection history exists,
select the current named node." t)
(autoload 'helix-treesit-go-parent-start "helix-treesit"
"Move to the start of the parent node in the syntax tree." t)
(autoload 'helix-treesit-go-parent-end "helix-treesit"
"Move to the end of the parent node in the syntax tree." t)
(autoload 'helix-treesit-setup "helix-treesit"
"Set up Helix Mode keybindings for tree-sitter.")
(register-definition-prefixes "helix-treesit" '("helix-treesit--"))

;;; End of scraped data

(provide 'helix-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helix-autoloads.el ends here
